[package]
name = "rust_file_mover"
version = "0.1.0"
authors = ["Cameron Eastman <ceastman77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust_file_mover"
path = "main.rs"
